/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(new Greeter("Hello!").sayHelloAndMessage(), "I am Alice. Hello!");
    }
}
