/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec;

public class App {

    public static void main(String[] args) {
        System.out.println(new Greeter("Hello World!").sayHelloAndMessage());
    }
}
