/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec;

public class Greeter {
    
    private final String message;

    public Greeter(String message) {
        this.message = message;
    }

    public String sayHelloAndMessage() {
        return "I am Alice. " + message;
    }
}
